apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-flask-app
  namespace: stellar
  labels:
    app: my-flask-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-flask-app
  template:
    metadata:
      labels:
        app: my-flask-app
    spec:
      containers:
      - name: flask-container
        image: $CI_REGISTRY_IMAGE/backend/flask:latest
        ports:
        - containerPort: 5000
        env:
        - name: DATABASE_URL
          value: "sqlite:///users.db"
      imagePullSecrets:
        - name: my-application-secret
