variables:
  FLASK_LATEST: $CI_REGISTRY_IMAGE/backend:latest
  NODE_LATEST: $CI_REGISTRY_IMAGE/backend:latest
stages:
  #- create_namespace_and_secret
  - make_docker_image
  - deploy
  - logs

.before script docker registry login: &before-script-docker-registry-login
  - mkdir ~/.docker
  - cat $CR_CONFIG > ~/.docker/config.json

make_flask_docker_image:
  stage: make_docker_image
  image: docker:latest
  before_script:
    - *before-script-docker-registry-login
  script:
    - cd backend/flask
    - docker build --pull -t $FLASK_LATEST .
    - docker push $FLASK_LATEST
  when: manual
  only:
    - main

make_node_docker_image:
  stage: make_docker_image
  image: docker:latest
  before_script:
    - *before-script-docker-registry-login
  script:
    - cd backend/node
    - docker build --pull -t $NODE_LATEST .
    - docker push $NODE_LATEST
  when: manual
  only:
    - main

deploy:
  stage: deploy
  image: hub.66bit.ru/shared/stk8s:1.26.2
  script:
    - kubectl delete -f ./cicd/kubernetes-deployment.yaml
    - kubectl apply -f ./cicd/kubernetes-persistent.yaml
    - kubectl apply -f ./cicd/kubernetes-deployment.yaml
  when: manual
  only:
    - main

logs:
  stage: logs
  image: hub.66bit.ru/shared/stk8s:1.26.2
  script:
    - kubectl logs -n stellar deploy/my-application-backend --since=30m
  when: manual
  only:
    - main