apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-node-app
  namespace: stellar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-node-app
  template:
    metadata:
      labels:
        app: my-node-app
    spec:
      containers:
      - name: my-node-app
        image: hub.66bit.ru/internship-2025/school-timeplanner/school-timeplanner/backend/node:latest
        ports:
        - containerPort: 3000
        env:
        - name: TELEGRAM_BOT_TOKEN
          value: "7688220876:AAEdlJxaqWj9ZBaJsKU_b8Mxu0oBSC99CPY"
      dnsConfig:
        options:
        - name: ndots
          value: "1"
      imagePullSecrets:
        - name: my-application-secret
