apiVersion: v1
kind: Service
metadata:
  name: my-node-app-service
  namespace: stellar
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 20000
  selector:
    app: my-node-app