apiVersion: v1
kind: Service
metadata:
  name: my-application-postgres-service
  namespace: stellar
spec:
  selector:
    app: my-application-database
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432